#!/usr/bin/env bun
/**
 * WildClawBench-CC runner — PilotDeck In-process Gateway edition.
 *
 * Parses WCB task .md files, prepares per-task workspaces, submits prompts
 * through PilotDeck's Gateway (in-process), collects workspace artifacts,
 * and runs the Python grade() function for scoring.
 *
 * Usage:
 *   node wcb/run_pilotdeck.mjs --task <task.md> [--output-dir <dir>] [--timeout <ms>]
 *   node wcb/run_pilotdeck.mjs --category <category_dir> [--limit N] [--filter <substr>]
 */

import { resolve, basename, dirname, join } from "node:path";
import { existsSync, readFileSync, writeFileSync, mkdirSync, cpSync, readdirSync, appendFileSync, symlinkSync, lstatSync } from "node:fs";
import { execSync, spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { createLocalGateway } from "../dist/src/cli/createLocalGateway.js";
import { installGlobalProxy } from "../dist/src/cli/proxy.js";

// ── Constants ──────────────────────────────────────────────────────────

const PILOTDECK_ROOT = resolve(dirname(new URL(import.meta.url).pathname), "..");
const WCB_ROOT = resolve(process.env.WCB_ROOT ?? join(PILOTDECK_ROOT, "../WildClawBench/WildClawBench-github"));
const WCB_ORIG_ROOT = resolve(WCB_ROOT, "../WildClawBench-orig");
const WCB_CC_ROOT = resolve(WCB_ROOT, "../WildClawBench-cc");
const DEFAULT_TIMEOUT_MS = 900_000; // 15 minutes
const DEFAULT_MAX_TURNS = 100;

// ── Load WCB .env if present ───────────────────────────────────────────

function loadDotEnv(envPath) {
  if (!existsSync(envPath)) return;
  const lines = readFileSync(envPath, "utf-8").split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx <= 0) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    let val = trimmed.slice(eqIdx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (!process.env[key]) process.env[key] = val;
  }
}

loadDotEnv(join(WCB_ROOT, ".env"));

// ── Ensure PilotDeck config exists ─────────────────────────────────────

function ensurePilotConfig(modelOverride) {
  const pilotHome = process.env.PILOT_HOME || join(process.env.HOME ?? "/root", ".pilotdeck");
  const configPath = join(pilotHome, "pilotdeck.yaml");
  if (existsSync(configPath)) return;

  const apiKey = process.env.EDGECLAW_API_KEY || process.env.OPENROUTER_API_KEY || process.env.ANTHROPIC_API_KEY;
  let baseUrl = process.env.EDGECLAW_API_BASE_URL || "https://openrouter.ai/api/v1";
  if (baseUrl.endsWith("/api") && !baseUrl.endsWith("/v1")) baseUrl += "/v1";
  const rawModel = modelOverride || process.env.EDGECLAW_MODEL || process.env.ANTHROPIC_MODEL || "claude-sonnet-4-20250514";
  const orchModel = process.env.ORCH_MODEL || "";
  const isAnthropicModel = !orchModel && (rawModel.includes("claude") || rawModel.startsWith("anthropic/"));
  const provider = isAnthropicModel ? "anthropic" : (baseUrl.includes("anthropic.com") ? "anthropic" : "openai");
  const modelId = isAnthropicModel && rawModel.startsWith("anthropic/") ? rawModel.slice("anthropic/".length) : rawModel;

  if (!apiKey) {
    console.error("ERROR: No API key found. Set EDGECLAW_API_KEY, OPENROUTER_API_KEY, or ANTHROPIC_API_KEY.");
    process.exit(1);
  }

  mkdirSync(pilotHome, { recursive: true });
  const modelRef = `${provider}/${modelId}`;

  let yaml;
  if (orchModel) {
    const orchBaseUrl = baseUrl.replace(/\/v1\/?$/, "");
    const useOpenAIForOrch = process.env.ORCH_VIA_OPENAI === "1";
    const orchProvider = useOpenAIForOrch ? "openai_orch" : "anthropic";
    const orchProtocol = useOpenAIForOrch ? "openai" : "anthropic";
    const orchUrl = useOpenAIForOrch ? baseUrl : orchBaseUrl;
    const orchModelId = useOpenAIForOrch ? `anthropic/${orchModel}` : orchModel;
    const orchRef = `${orchProvider}/${orchModelId}`;
    const judgeModel = "google/gemini-2.5-flash";
    const judgeRef = `openai_judge/${judgeModel}`;
    yaml = `# Auto-generated by wcb/run_pilotdeck.mjs (orchestration mode, dual-provider)
agent:
  model: "${orchRef}"

model:
  providers:
    ${provider}:
      protocol: ${provider}
      url: "${baseUrl}"
      apiKey: "${apiKey}"
      models:
        "${modelId}":
          id: "${modelId}"
          displayName: "${modelId}"
          capabilities:
            contextWindow: 65536
            maxOutputTokens: 16384
            streaming: true
            tools: true
            vision: false
          multimodal:
            input:
              - text
    openai_judge:
      protocol: openai
      url: "${baseUrl}"
      apiKey: "${apiKey}"
      models:
        "${judgeModel}":
          id: "${judgeModel}"
          displayName: "Gemini 2.5 Flash (Judge)"
          capabilities:
            contextWindow: 1048576
            maxOutputTokens: 8192
            streaming: true
            tools: false
            vision: false
          multimodal:
            input:
              - text
    ${orchProvider}:
      protocol: ${orchProtocol}
      url: "${orchUrl}"
      apiKey: "${apiKey}"${useOpenAIForOrch ? "" : `
      headers:
        anthropic-beta: "prompt-caching-2024-07-31"
      extraBody:
        provider:
          order:
            - "Anthropic"
          allow_fallbacks: false`}
      models:
        "${orchModelId}":
          id: "${orchModelId}"
          displayName: "${orchModel}"
          capabilities:
            contextWindow: 200000
            maxOutputTokens: 16384
            streaming: true
            tools: true
            vision: false${useOpenAIForOrch ? "" : `
            supportsPromptCache: true`}
          multimodal:
            input:
              - text

router:
  scenarios:
    default: "${orchRef}"
  tokenSaver:
    enabled: true
    judge: "${judgeRef}"
    judgeTimeoutMs: 15000
    defaultTier: medium
    tiers:
      simple:
        model: "${modelRef}"
        description: "Simple greetings, confirmations, single-step Q&A, status checks, remembering rules"
      medium:
        model: "${modelRef}"
        description: "Focused single-objective tasks: reading/writing files, data processing, code generation for one module, chart/visualization creation, single-format document generation, or any delegated subtask with a clear single deliverable"
      reasoning:
        model: "${orchRef}"
        description: "Pure reasoning or analysis on already-available data, no heavy tool use needed"
      complex:
        model: "${orchRef}"
        description: "Tasks requiring coordination across MULTIPLE distinct objectives or deliverable types simultaneously — e.g. a full project needing data+charts+report+analysis together, or tasks requiring web research combined with multi-file code changes"
    rules:
      - "If the task focuses on ONE deliverable type (only data merge, only charts, only a report, only code), classify as medium"
      - "Only classify as complex when the task requires MULTIPLE different deliverable types produced together in one session"
      - "Subtasks delegated from an orchestrator (marked with <pilotdeck-fork>) should default to medium unless they explicitly require multiple distinct deliverable types"
      - "Only use reasoning for pure thinking tasks that need no file writes or tool chains"
      - "When in doubt between medium and complex, prefer medium"
    subagent:
      policy: judge
  autoOrchestrate:
    enabled: true
    triggerTiers:
${(process.env.ORCH_TRIGGER_TIERS || "complex").split(",").map(t => `      - ${t.trim()}`).join("\n")}
    mainAgentModel: "${orchRef}"
    slimSystemPrompt: true
  zeroUsageRetry:
    enabled: true
    maxAttempts: 2
  transientRetry:
    enabled: true
    maxAttempts: 3
    baseDelayMs: 2000
    maxDelayMs: 15000
  stats:
    enabled: true
    modelPricing:
      "${orchRef}":
        input: 3.0
        output: 15.0
        cacheRead: 0.30
`;
    console.log(`[setup] Created ${configPath} (orchestration dual-provider: worker=${modelRef}, orchestrator=${orchRef}, retry enabled)`);
  } else if (isAnthropicModel) {
    const anthropicUrl = baseUrl.replace(/\/v1\/?$/, "");
    const agentModelRef = `anthropic/${modelId}`;
    yaml = `# Auto-generated by wcb/run_pilotdeck.mjs (Anthropic single-agent + prompt caching)
agent:
  model: "${agentModelRef}"

model:
  providers:
    anthropic:
      protocol: anthropic
      url: "${anthropicUrl}"
      apiKey: "${apiKey}"
      headers:
        anthropic-beta: "prompt-caching-2024-07-31"
      extraBody:
        provider:
          order:
            - "Anthropic"
          allow_fallbacks: false
      models:
        "${modelId}":
          id: "${modelId}"
          displayName: "${modelId}"
          capabilities:
            contextWindow: 200000
            maxOutputTokens: 16384
            streaming: true
            tools: true
            vision: false
            supportsPromptCache: true
          multimodal:
            input:
              - text

router:
  scenarios:
    default: "${agentModelRef}"
  zeroUsageRetry:
    enabled: true
    maxAttempts: 2
  transientRetry:
    enabled: true
    maxAttempts: 3
    baseDelayMs: 2000
    maxDelayMs: 15000
  stats:
    enabled: true
    modelPricing:
      "${agentModelRef}":
        input: 3.0
        output: 15.0
        cacheRead: 0.30
`;
    console.log(`[setup] Created ${configPath} (Anthropic single-agent: ${agentModelRef}, prompt caching ON, retry enabled)`);
  } else {
    const agentModelRef = `${provider}/${modelId}`;
    yaml = `# Auto-generated by wcb/run_pilotdeck.mjs
agent:
  model: "${agentModelRef}"

model:
  providers:
    ${provider}:
      protocol: ${provider}
      url: "${baseUrl}"
      apiKey: "${apiKey}"
      models:
        "${modelId}":
          id: "${modelId}"
          displayName: "${modelId}"
          capabilities:
            contextWindow: 65536
            maxOutputTokens: 16384
            streaming: true
            tools: true
            vision: false
          multimodal:
            input:
              - text

router:
  scenarios:
    default: "${modelRef}"
  tokenSaver:
    enabled: true
    judge: "${modelRef}"
    defaultTier: medium
    tiers:
      simple:
        model: "${modelRef}"
      medium:
        model: "${modelRef}"
      reasoning:
        model: "${modelRef}"
      complex:
        model: "${modelRef}"
  stats:
    enabled: true
`;
    console.log(`[setup] Created ${configPath} (agent.model=${agentModelRef}, router=tokenSaver+stats)`);
  }
  writeFileSync(configPath, yaml);
}

// Config is created lazily in runTask after PILOT_HOME is set

// ── CLI Argument Parsing ───────────────────────────────────────────────

function parseArgs(argv) {
  const args = {
    task: null,
    category: null,
    filter: "",
    limit: 0,
    outputDir: null,
    timeoutMs: DEFAULT_TIMEOUT_MS,
    maxTurns: DEFAULT_MAX_TURNS,
    skipGrading: false,
    model: null,
    bugsFile: null,
    configTemplate: null,
  };
  for (let i = 2; i < argv.length; i++) {
    const flag = argv[i];
    const next = argv[i + 1];
    switch (flag) {
      case "--task":       args.task = next; i++; break;
      case "--category":   args.category = next; i++; break;
      case "--filter":     args.filter = next; i++; break;
      case "--limit":      args.limit = parseInt(next, 10); i++; break;
      case "--output-dir": args.outputDir = next; i++; break;
      case "--timeout":    args.timeoutMs = parseInt(next, 10); i++; break;
      case "--max-turns":  args.maxTurns = parseInt(next, 10); i++; break;
      case "--skip-grading": args.skipGrading = true; break;
      case "--model":      args.model = next; i++; break;
      case "--bugs-file":  args.bugsFile = next; i++; break;
      case "--config":     args.configTemplate = next; i++; break;
      default:
        if (!flag.startsWith("-")) args.task = flag;
    }
  }
  return args;
}

// ── Bug Logger ──────────────────────────────────────────────────────────

function appendBug(bugsFile, taskId, type, msg, context) {
  if (!bugsFile) return;
  const entry = {
    ts: new Date().toISOString(),
    taskId,
    type,
    msg: String(msg).slice(0, 500),
    context: context ?? {},
  };
  try {
    mkdirSync(dirname(bugsFile), { recursive: true });
    appendFileSync(bugsFile, JSON.stringify(entry) + "\n");
  } catch { /* best-effort */ }
}

// ── Task Parser (mirrors Python task_parser.py) ────────────────────────

async function parseTaskMd(taskFile) {
  const content = readFileSync(taskFile, "utf-8");
  const fmMatch = content.match(/^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)/);
  if (!fmMatch) throw new Error(`YAML frontmatter not found: ${taskFile}`);

  const YAML = await import("yaml");
  const metadata = YAML.parse(fmMatch[1]);
  const body = fmMatch[2];

  const sections = {};
  let currentSection = null;
  let lines = [];
  for (const line of body.split("\n")) {
    const header = line.match(/^##\s+(.+)$/);
    if (header) {
      if (currentSection !== null) sections[currentSection] = lines.join("\n").trim();
      currentSection = header[1];
      lines = [];
    } else {
      lines.push(line);
    }
  }
  if (currentSection !== null) sections[currentSection] = lines.join("\n").trim();

  const stripCodeblock = (raw) => raw.replace(/^```[^\n]*\n?/, "").replace(/\n?```$/, "").trim();

  const prompt = (sections["Prompt"] ?? "").trim();
  let workspacePath = stripCodeblock(sections["Workspace Path"] ?? "");
  if (!workspacePath) throw new Error(`Missing ## Workspace Path in: ${taskFile}`);

  const automatedChecks = stripCodeblock(sections["Automated Checks"] ?? "");
  const env = stripCodeblock(sections["Env"] ?? "");
  const skills = stripCodeblock(sections["Skills"] ?? "");
  const warmup = stripCodeblock(sections["Warmup"] ?? "");
  const taskId = metadata.id ?? basename(taskFile, ".md");
  const timeoutSeconds = parseInt(metadata.timeout_seconds ?? "120", 10);

  if (!workspacePath.startsWith("/")) {
    const candidates = [WCB_ROOT, WCB_ORIG_ROOT, WCB_CC_ROOT];
    let found = false;
    for (const root of candidates) {
      const candidate = resolve(root, workspacePath);
      if (existsSync(candidate)) { workspacePath = candidate; found = true; break; }
    }
    if (!found) workspacePath = resolve(WCB_ROOT, workspacePath);
  }

  let skillsPath = resolve(WCB_ROOT, "skills");
  if (!existsSync(skillsPath)) skillsPath = resolve(WCB_ORIG_ROOT, "skills");
  if (!existsSync(skillsPath)) skillsPath = resolve(WCB_CC_ROOT, "skills");

  return {
    taskId,
    prompt,
    workspacePath,
    skillsPath,
    automatedChecks,
    env,
    skills,
    warmup,
    timeoutSeconds,
    filePath: resolve(taskFile),
    category: basename(dirname(resolve(taskFile))),
  };
}

// ── Workspace Preparation ──────────────────────────────────────────────

function prepareWorkspace(task, runDir) {
  const workDir = join(runDir, "workspace");
  mkdirSync(workDir, { recursive: true });

  if (existsSync(task.workspacePath)) {
    const execDir = join(task.workspacePath, "exec");
    if (existsSync(execDir)) {
      cpSync(execDir, workDir, { recursive: true, dereference: true });
      log(task.taskId, `Workspace copied from ${execDir} (exec/ flattened)`);
    } else {
      cpSync(task.workspacePath, workDir, { recursive: true, dereference: true });
      log(task.taskId, `Workspace copied from ${task.workspacePath}`);
    }
    const gtDir = join(task.workspacePath, "gt");
    if (existsSync(gtDir)) {
      cpSync(gtDir, join(workDir, "gt"), { recursive: true, dereference: true });
      log(task.taskId, `Ground truth copied from ${gtDir}`);
    }
  } else {
    log(task.taskId, `WARNING: workspace source not found: ${task.workspacePath}`);
  }

  mkdirSync(join(workDir, "results"), { recursive: true });
  return workDir;
}

// ── Environment Setup ──────────────────────────────────────────────────

function injectEnv(envSpec) {
  if (!envSpec) return;
  for (const line of envSpec.split("\n")) {
    const varName = line.trim();
    if (!varName || varName.startsWith("#")) continue;
    // Variable is referenced in the task — make sure it's in process.env
    // (it should already be set from the shell; this is a validation step)
    if (!process.env[varName]) {
      log("env", `WARNING: Task requires ${varName} but it is not set`);
    }
  }
}

// ── Logging ────────────────────────────────────────────────────────────

function log(taskId, ...args) {
  const ts = new Date().toISOString().slice(11, 19);
  console.log(`${ts} [${taskId}]`, ...args);
}

// ── Run Single Task ────────────────────────────────────────────────────

async function runTask(task, args) {
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const runName = `pilotdeck_${timestamp}`;
  const outputBase = args.outputDir
    ? resolve(args.outputDir)
    : resolve(WCB_ROOT, "output-pilotdeck");
  const runDir = join(outputBase, task.category, task.taskId, runName);
  mkdirSync(runDir, { recursive: true });

  log(task.taskId, `=== Starting task: ${task.taskId} ===`);
  log(task.taskId, `Output: ${runDir}`);

  // 0. Set PILOT_HOME per-task so transcripts land in the output directory
  const pilotHome = join(runDir, "transcripts");
  mkdirSync(pilotHome, { recursive: true });
  process.env.PILOT_HOME = pilotHome;
  if (args.configTemplate && existsSync(args.configTemplate)) {
    cpSync(args.configTemplate, join(pilotHome, "pilotdeck.yaml"));
    log(task.taskId, `Config copied from template: ${args.configTemplate}`);
  }
  ensurePilotConfig(args.model);

  // 0.5 Copy WCB skills into $PILOT_HOME/skills/ (mirrors Claude Code ~/.claude/skills/)
  {
    const skillNames = task.skills
      ? task.skills.split("\n").map(l => l.trim()).filter(Boolean)
      : existsSync(task.skillsPath)
        ? readdirSync(task.skillsPath).filter(n => {
            try { return lstatSync(join(task.skillsPath, n)).isDirectory(); } catch { return false; }
          })
        : [];
    for (const skillName of skillNames) {
      const src = join(task.skillsPath, skillName);
      const dst = join(pilotHome, "skills", skillName);
      if (existsSync(src)) {
        mkdirSync(dst, { recursive: true });
        cpSync(src, dst, { recursive: true });
        log(task.taskId, `Skill copied: ${skillName} -> ${dst}`);
      } else {
        log(task.taskId, `WARNING: Skill not found: ${src}`);
      }
    }
  }

  // 0.6 Symlink ~/.claude/skills/ -> $PILOT_HOME/skills/ so task prompts
  //     referencing ~/.claude/skills/ resolve to PilotDeck's skill directory
  const claudeSkillsDir = join(process.env.HOME ?? "/root", ".claude", "skills");
  const pilotSkillsDir = join(pilotHome, "skills");
  try {
    if (!existsSync(claudeSkillsDir)) {
      mkdirSync(dirname(claudeSkillsDir), { recursive: true });
      symlinkSync(pilotSkillsDir, claudeSkillsDir);
      log(task.taskId, `Symlinked ${claudeSkillsDir} -> ${pilotSkillsDir}`);
    }
  } catch (e) {
    log(task.taskId, `WARNING: Could not symlink ~/.claude/skills/: ${e.message}`);
  }

  // 1. Prepare workspace
  const workDir = prepareWorkspace(task, runDir);

  // 2. Inject environment variables
  injectEnv(task.env);

  // 3. Run warmup commands
  if (task.warmup) {
    log(task.taskId, `Running warmup: ${task.warmup.slice(0, 80)}...`);
    try {
      execSync(task.warmup, { cwd: workDir, stdio: "pipe", timeout: 120_000 });
    } catch (e) {
      log(task.taskId, `Warmup failed (non-fatal): ${e.message}`);
      appendBug(args.bugsFile, task.taskId, "warmup_error", e.message);
    }
  }

  // 4. Rewrite prompt paths: /tmp_workspace/ → actual workDir
  const rewrittenPrompt = task.prompt.replaceAll("/tmp_workspace", workDir);

  // 5. Create PilotDeck Gateway and run agent
  const timeoutMs = Math.min(task.timeoutSeconds * 1000, args.timeoutMs);
  log(task.taskId, `Timeout: ${timeoutMs / 1000}s | Model: ${args.model ?? "default"}`);

  const startTime = Date.now();
  const events = [];
  let assistantText = "";
  let assistantThinking = "";
  let usage = {};
  let finishReason = "unknown";
  let error = null;

  try {
    installGlobalProxy();

    const { gateway } = createLocalGateway({
      projectRoot: workDir,
      pilotHome,
      permissionMode: "bypassPermissions",
      autoElicitation: true,
      additionalWorkingDirectories: ["/tmp", "/workspace"],
      env: { ...process.env },
    });

    const { sessionKey } = await gateway.newSession({
      channelKey: "test",
      projectKey: workDir,
    });

    log(task.taskId, `Session: ${sessionKey}`);

    const abortController = new AbortController();
    let timedOut = false;
    const timer = setTimeout(() => {
      timedOut = true;
      log(task.taskId, `TIMEOUT after ${timeoutMs / 1000}s — aborting`);
      appendBug(args.bugsFile, task.taskId, "timeout", `Agent timed out after ${timeoutMs / 1000}s`, { events: events.length });
      gateway.abortTurn({ sessionKey }).catch(() => {});
      abortController.abort();
    }, timeoutMs);

    try {
      const stream = gateway.submitTurn({
        sessionKey,
        channelKey: "test",
        message: rewrittenPrompt,
        projectKey: workDir,
        mode: "bypassPermissions",
        maxTurns: args.maxTurns,
      });

      for await (const event of stream) {
        events.push({ ...event, ts: Date.now() - startTime });

        switch (event.type) {
          case "turn_started":
            log(task.taskId, "Turn started");
            break;
          case "assistant_text_delta":
            assistantText += event.text;
            break;
          case "assistant_thinking_delta":
            assistantThinking += event.text;
            break;
          case "tool_call_started":
            log(task.taskId, `Tool: ${event.name}`);
            break;
          case "tool_call_finished":
            log(task.taskId, `Tool done: ${event.toolCallId} ok=${event.ok}`);
            break;
          case "turn_completed":
            usage = event.usage ?? {};
            finishReason = event.finishReason ?? "completed";
            log(task.taskId, `Turn completed: ${finishReason}`);
            break;
          case "agent_status": {
            const d = event.detail ?? {};
            switch (event.event) {
              case "compact_started":
                log(task.taskId, `Compact: started (trigger=${d.trigger} pre=${d.preTokens})`);
                break;
              case "compact_completed":
                log(task.taskId, `Compact: done (${d.status} ${d.preTokens}→${d.postTokens ?? "?"})`);
                break;
              case "turn_continued":
                log(task.taskId, `Turn continued: ${d.reason}`);
                break;
              case "subagent_started":
                log(task.taskId, `Subagent: ${d.subagentType}/${d.subagentId} started`);
                break;
              case "subagent_completed":
                log(task.taskId, `Subagent: ${d.subagentType}/${d.subagentId} done (ok=${d.success} ${d.durationMs}ms)`);
                break;
              default:
                log(task.taskId, `Status: ${event.event} ${JSON.stringify(d)}`);
            }
            break;
          }
          case "error":
            log(task.taskId, `ERROR: [${event.code}] ${event.message}`);
            if (!event.recoverable) {
              error = event.message;
              appendBug(args.bugsFile, task.taskId, "model_error", event.message, { code: event.code });
            }
            break;
        }
      }
    } finally {
      clearTimeout(timer);
    }

    if (timedOut) finishReason = "timeout";

    await gateway.closeSession({ sessionKey, reason: "task_complete" });
  } catch (e) {
    error = e.message ?? String(e);
    log(task.taskId, `FATAL: ${error}`);
    appendBug(args.bugsFile, task.taskId, "crash", error);
  }

  const elapsed = Date.now() - startTime;
  log(task.taskId, `Elapsed: ${(elapsed / 1000).toFixed(1)}s`);

  // 6. Save metadata
  const meta = {
    taskId: task.taskId,
    category: task.category,
    runner: "pilotdeck-in-process",
    model: args.model ?? process.env.EDGECLAW_MODEL ?? "default",
    pilotHome,
    startTime: new Date(startTime).toISOString(),
    elapsedMs: elapsed,
    finishReason,
    usage,
    error,
    eventCount: events.length,
  };
  writeFileSync(join(runDir, "task-meta.json"), JSON.stringify(meta, null, 2));
  writeFileSync(join(runDir, "events.jsonl"), events.map((e) => JSON.stringify(e)).join("\n") + "\n");
  const finalAssistantOutput = assistantText || assistantThinking;
  if (finalAssistantOutput) writeFileSync(join(runDir, "assistant.md"), finalAssistantOutput);
  if (error) writeFileSync(join(runDir, "error.txt"), error);

  // 7. Copy workspace results to output
  const resultsDir = join(workDir, "results");
  const outputResults = join(runDir, "results");
  if (existsSync(resultsDir)) {
    cpSync(resultsDir, outputResults, { recursive: true });
    log(task.taskId, `Results collected → ${outputResults}`);
  }

  // 8. Log transcript file inventory
  logTranscriptInventory(task.taskId, pilotHome);

  // 9. Grading
  let scores = null;
  if (!args.skipGrading && task.automatedChecks) {
    scores = await runGrading(task, workDir, runDir);
    if (scores?.error) {
      appendBug(args.bugsFile, task.taskId, "grading_error", scores.error);
    }
  }

  return { taskId: task.taskId, runDir, elapsed, finishReason, usage, error, scores };
}

// ── Transcript Inventory ────────────────────────────────────────────────

function logTranscriptInventory(taskId, pilotHome) {
  try {
    const projectsDir = join(pilotHome, "projects");
    if (!existsSync(projectsDir)) {
      log(taskId, "No transcripts found (projects/ missing)");
      return;
    }
    let mainCount = 0, subCount = 0, toolResultCount = 0;
    const walk = (dir) => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = join(dir, entry.name);
        if (entry.isDirectory()) {
          walk(full);
        } else if (entry.name.endsWith(".jsonl")) {
          if (full.includes("/subagents/")) subCount++;
          else mainCount++;
        } else if (full.includes("/tool-results/")) {
          toolResultCount++;
        }
      }
    };
    walk(projectsDir);
    log(taskId, `Transcripts: ${mainCount} main, ${subCount} subagent, ${toolResultCount} tool-results`);
    const statsPath = join(pilotHome, "router-stats.json");
    if (existsSync(statsPath)) {
      log(taskId, `Router stats: ${statsPath}`);
    }
  } catch (e) {
    log(taskId, `Transcript inventory error: ${e.message}`);
  }
}

// ── Grading (calls Python) ─────────────────────────────────────────────

async function runGrading(task, workDir, runDir) {
  log(task.taskId, "Running grading...");

  const rewrittenChecks = task.automatedChecks.replaceAll("/tmp_workspace", workDir);

  const gradeScript = `
import json, sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

${rewrittenChecks}

result = grade(transcript=[], workspace_path="${workDir.replace(/\\/g, "/")}")
print(json.dumps(result))
`.trim();

  const gradePath = join(runDir, "_grade.py");
  writeFileSync(gradePath, gradeScript);

  return new Promise((resolve) => {
    const proc = spawn("python3", [gradePath], {
      cwd: WCB_ROOT,
      timeout: 120_000,
      env: { ...process.env },
    });
    let stdout = "";
    let stderr = "";
    proc.stdout.on("data", (d) => (stdout += d));
    proc.stderr.on("data", (d) => (stderr += d));
    proc.on("close", (code) => {
      if (code !== 0) {
        log(task.taskId, `Grading failed (exit ${code}): ${stderr.slice(0, 300)}`);
        const errResult = { error: `grade exit ${code}: ${stderr.slice(0, 200)}` };
        writeFileSync(join(runDir, "score.json"), JSON.stringify(errResult, null, 2));
        resolve(errResult);
        return;
      }
      try {
        let scores = null;
        for (const line of stdout.trim().split("\n").reverse()) {
          const trimmed = line.trim();
          if (trimmed.startsWith("{")) {
            try { scores = JSON.parse(trimmed); break; } catch {}
          }
        }
        if (!scores) throw new Error("No valid JSON in grade output");
        writeFileSync(join(runDir, "score.json"), JSON.stringify(scores, null, 2));
        log(task.taskId, `Grading done: ${JSON.stringify(scores)}`);
        resolve(scores);
      } catch (e) {
        const errResult = { error: `json parse: ${e.message}` };
        writeFileSync(join(runDir, "score.json"), JSON.stringify(errResult, null, 2));
        resolve(errResult);
      }
    });
  });
}

// ── Task Discovery ─────────────────────────────────────────────────────

function discoverTasks(categoryDir, filter, limit) {
  let tasksDir = null;
  for (const root of [WCB_ROOT, WCB_ORIG_ROOT, WCB_CC_ROOT]) {
    const candidate = resolve(root, "tasks", categoryDir);
    if (existsSync(candidate)) { tasksDir = candidate; break; }
  }
  if (!tasksDir) {
    console.error(`Tasks directory not found in WCB-github, WCB-orig, or WCB-cc: ${categoryDir}`);
    process.exit(1);
  }
  let files = readdirSync(tasksDir)
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => join(tasksDir, f));

  if (filter) files = files.filter((f) => f.includes(filter));
  if (limit > 0) files = files.slice(0, limit);

  return files;
}

// ── Main ───────────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs(process.argv);

  if (!args.task && !args.category) {
    console.error(`Usage:
  bun wcb/run_pilotdeck.mjs --task <path/to/task.md> [options]
  bun wcb/run_pilotdeck.mjs --category <category_dir> [--filter <substr>] [--limit N]

Options:
  --output-dir <dir>    Output directory (default: WCB_ROOT/output-pilotdeck)
  --timeout <ms>        Per-task timeout in ms (default: 600000)
  --max-turns <n>       Max agent turns (default: 100)
  --model <model>       Override model (e.g. deepseek/deepseek-v4-flash)
  --bugs-file <path>    Append bugs to this JSONL file
  --skip-grading        Skip Python grading step
`);
    process.exit(1);
  }

  let taskFiles = [];
  if (args.task) {
    taskFiles = [resolve(args.task)];
  } else {
    taskFiles = discoverTasks(args.category, args.filter, args.limit);
  }

  log("main", `Found ${taskFiles.length} task(s)`);

  const results = [];
  for (const taskFile of taskFiles) {
    const task = await parseTaskMd(taskFile);
    const result = await runTask(task, args);
    results.push(result);
    console.log("");
  }

  // Summary
  console.log("\n" + "=".repeat(60));
  console.log("  WCB-CC PilotDeck Runner — Summary");
  console.log("=".repeat(60));
  for (const r of results) {
    const status = r.error ? "FAIL" : "OK";
    const scoreStr = r.scores && !r.scores.error
      ? Object.entries(r.scores)
          .filter(([, v]) => typeof v === "number")
          .map(([k, v]) => `${k}=${v.toFixed(2)}`)
          .join(" ")
      : r.scores?.error ?? "n/a";
    console.log(`  [${status}] ${r.taskId}  ${(r.elapsed / 1000).toFixed(1)}s  ${scoreStr}`);
  }
  console.log("=".repeat(60));
}

main().then(() => {
  forceExit(0);
}).catch((e) => {
  console.error("Fatal:", e);
  forceExit(1);
});

function forceExit(code) {
  // Playwright MCP and other child processes may linger after the agent
  // session ends, preventing `process.exit` from completing inside Docker.
  // Kill the entire process group first, then hard-exit after a grace period.
  try { process.kill(-process.pid, "SIGTERM"); } catch { /* not a group leader */ }
  setTimeout(() => {
    try { process.kill(-process.pid, "SIGKILL"); } catch { /* ignore */ }
    process.exit(code);
  }, 1500).unref();
  process.exit(code);
}
